### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by PerfectionCat** [Ryan-rsm-McKenzie/CommonLibSSE#11]
Is this correct?
`	bool TESObjectREFR::MoveToNode(TESObjectREFR* a_target, NiAVObject* a_node)
	{
		auto& position = a_node->world.translate;
		NiPoint3 rotation;
		a_node->world.rotate.ToEulerAnglesXYZ(rotation);
		auto handle = a_target->CreateRefHandle();
		MoveTo_Impl(handle, a_target->GetParentCell(), GetWorldspace(), position, rotation);
		return true;
	}
`

**Comment by Ryan-rsm-McKenzie** [comment]
it should be fixed
