### ISSUE TITLE
linux guide

### ISSUE THREAD

**Issue by CrezyDud** [Ryan-rsm-McKenzie/CommonLibSSE#117]
Linux users don't have msvc
but i'd like to make a mod
can you make a guide for linux?

**Comment by Ryan-rsm-McKenzie** [comment]
This is a windows only library

**Comment by CrezyDud** [comment]
i understand, but i'll compile it to a .dll
to use it with skyrim
isn't there an option in msvc to generate cmake files
so i could build it, could you do that?

**Comment by Ryan-rsm-McKenzie** [comment]
This will not build on linux, it will not build with gcc, and it will not build with clang.
This is a windows only library made for msvc

**Comment by CrezyDud** [comment]
ever heard of mingw?
it allow cross-compilation from linux to windows

**Comment by Ryan-rsm-McKenzie** [comment]
It will not compile with a port of gcc either

**Comment by CrezyDud** [comment]
bruh you really don't get it do you?

**Comment by CrezyDud** [comment]
> It will not compile with a port of gcc either

R E S E A R C H

**Comment by CrezyDud** [comment]
https://www.crossmeta.io/mingw32-cross-compile-to-windows-from-linux/

OOPS LOOKS LIKE IT DOES
