### ISSUE TITLE
Building error with Logger (or maybe fmt)

### ISSUE THREAD

**Issue by maboroshinokiseki** [Ryan-rsm-McKenzie/CommonLibSSE#120]
I followed getting start, and while compiling, it shows some error like the following

C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\include\SKSE/Logger.h(39,2): error C7595: 'fmt::v8::basic_format_string<char,const char *&>::basic_format_string': call to immediate f unction is not a constant expression (compiling source file C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\src\SKSE\Interfaces.cpp) [C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonL ibSSE\build\src\CommonLibSSE\CommonLibSSE.vcxproj]
C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\include\SKSE/Logger.h(39,2): message : failure was caused by a read of a variable outside its lifetime (compiling source file C:\Users \Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\src\SKSE\Interfaces.cpp) [C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\build\src\CommonLibSSE\CommonLibSSE.vcxproj]
C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\include\SKSE/Logger.h(39,2): message : see usage of 'a_fmt' (compiling source file C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibS SE\external\CommonLibSSE\src\SKSE\Interfaces.cpp) [C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\build\src\CommonLibSSE\CommonLibSSE.vcxproj]
C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\src\SKSE\Interfaces.cpp(70): message : see reference to function template instantiation 'SKSE::log::error<const char *&>::error<const
char(&)[55]>(T,const char *&,std::source_location)' being compiled [C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\build\src\CommonLibSSE\CommonLibSSE.vcxproj]
          with
          [
              T=const char (&)[55]
          ]
C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\external\CommonLibSSE\src\SKSE\Interfaces.cpp(70): message : see reference to function template instantiation 'SKSE::log::error<const char *&>::error<const
char(&)[55]>(T,const char *&,std::source_location)' being compiled [C:\Users\Maboroshi\source\repos\ExamplePlugin-CommonLibSSE\build\src\CommonLibSSE\CommonLibSSE.vcxproj]
          with
          [
              T=const char (&)[55]
          ]

**Comment by alandtse** [comment]
It's caused by an update in vcpkg that took  `fmt` to 8.1.0. You can workaround it until someone can fix it by dropping fmt down to 8.0.1 using `overrides`.

Please note the `builtin-baseline` key will likely need to be changed for you.

vcpkg.json
```json
{
   "name":"commonlibsse",
   "version-string":"1",
   "description":"A reverse engineered resource for developing F4SE plugins for Skyrim Special Edition",
   "homepage":"https://github.com/Ryan-rsm-McKenzie/CommonLibSSE",
   "license":"MIT",
   "supports":"windows & x64",
   "dependencies":[
      "boost-stl-interfaces",
      "rsm-binary-io",
      "spdlog"
   ],
   "builtin-baseline":"bba8794b82a0f44b8709f294850a2c8e96b61415",
   "overrides":[
      {
         "name":"fmt",
         "version":"8.0.1"
      }
   ]
}

```

**Comment by maboroshinokiseki** [comment]
Thank you for your reply

**Comment by alandtse** [comment]
It may be worth keeping it open until it's formally fixed instead of a workaround.

**Comment by maboroshinokiseki** [comment]
> It may be worth keeping it open until it's formally fixed instead of a workaround.

It seems like that the author just fixed it :D
