### ISSUE TITLE
Using CommonLib with Example Plugin

### ISSUE THREAD

**Issue by Elscrux** [Ryan-rsm-McKenzie/CommonLibSSE#13]
I'm trying to use CommonLib with your  ExamplePlugin-CommonLibSSE and followed Setting Up Your Environment in your tutorial, thank you for that btw.
I extracted CommonLib and the MyFirstPlugin to the src/skse64 folder and added them to VS.
![Directory](https://user-images.githubusercontent.com/34755314/74610571-9e854d80-50f4-11ea-85d0-6f9fe1f21f73.png)
I noticed some reference issues. I could resolve the CommonLibSSE in MyFirstPlugin issue by removing it and adding it back again. When I tried to do the same for the skse64 reference in CommonLibSSE it didn't resolve the error (The "Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProjectReference" reference could not be resolved.)
![References](https://user-images.githubusercontent.com/34755314/74610142-ca9ecf80-50f0-11ea-91b0-b3393e7db85c.png)
In the main.cpp of MyFirstPlugin were some errors as well.
![main1](https://user-images.githubusercontent.com/34755314/74610346-e1462600-50f2-11ea-861c-10e0e22e2966.png)
I resolved them like this by adding some recommended includes and changing FOLDERID_Documents to FOLDERTYPEID_Documents
![main2](https://user-images.githubusercontent.com/34755314/74610451-a55f9080-50f3-11ea-92e6-3097de9a7fc1.png)
When I try to build MyFirstPlugin there are lots of errors
![Errors](https://user-images.githubusercontent.com/34755314/74610561-93322200-50f4-11ea-8e1b-b6be436a837a.png)
I'm thinking this is due to the skse64 reference in CommonLibSSE that is not working correctly?
What am I doing wrong?
I'd be grateful for any help 😃

**Comment by grazz** [comment]
just disable warnings as errors and it will build, but that's probably there for a reason

**Comment by Elscrux** [comment]
Yes, it works for compiling but this error shows up on startup.
![Crash](https://user-images.githubusercontent.com/34755314/75369579-03def880-58c4-11ea-952f-ead2de0a1547.png)

**Comment by grazz** [comment]
what revision are you using?

**Comment by Elscrux** [comment]
the latest

**Comment by grazz** [comment]
use commonlibsse revision a5e3617667a2ea296b67da549e31fe26543ecb8a for now

**Comment by grazz** [comment]
use commonlibsse revision `a5e3617667a2ea296b67da549e31fe26543ecb8a` for now

**Comment by Ryan-rsm-McKenzie** [comment]
The bins are from [here](https://www.nexusmods.com/skyrimspecialedition/mods/32444)

**Comment by grazz** [comment]
thank you very much

**Comment by Elscrux** [comment]
Thanks to you both. Everything is working now!
