### ISSUE TITLE
the library appears to require upstream code to use Platform v142

### ISSUE THREAD

**Issue by SteveTownsend** [Ryan-rsm-McKenzie/CommonLibSSE#18]
People have hit issues deploying my mod based on CLSSE because my DLL requires Visual C++ Runtime 2015-2019 (x64) to be present. One of my early downloaders does not have this VC++ runtime yet.  

I confirmed locally that if I uninstall this, MO2 won't start SkyrimSE through SKSE. That's not a definitive repro, but supports the idea that this runtime is a hard requirement I am adding.

I am building with Platform Toolset v142 (2019). If I alter this to 2015 (v140) I get an error because <optional> in CLSSEs' PCH.H is not found.  

If there's a work round where I can ship my plugin not requiring this newer Visual C++ runtime it would be preferable. I have added mod page instructions on how to install the runtime but that's a big tax on users. **If this is the way it is, that's fine though.** The price of progress!

Thanks for your thoughts.

**Comment by Ryan-rsm-McKenzie** [comment]
You can change to project settings to link the crt statically

**Comment by SteveTownsend** [comment]
Thanks, I have that built but the victim worked around it willingly and
with success. I'll see how often this comes up, I imagine Windows 10 forced
updates will get people who lag up to date pretty soon.
