### ISSUE TITLE
Wrong GetNum?

### ISSUE THREAD

**Issue by r-neal-kelly** [Ryan-rsm-McKenzie/CommonLibSSE#22]
https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/9cfb821652df4b854603bec0cfae093b9856374c/src/RE/BSScript/ObjectTypeInfo.cpp#L245

Should this be GetNumProperties instead?

**Comment by Ryan-rsm-McKenzie** [comment]
fixed
