### ISSUE TITLE
Example plugin compile error

### ISSUE THREAD

**Issue by thallada** [Ryan-rsm-McKenzie/CommonLibSSE#23]
Hi, thank you for this library and your very helpful tutorial.

I'm new to C++, and I'm having trouble setting up [the example plugin](https://github.com/Ryan-rsm-McKenzie/ExamplePlugin-CommonLibSSE). I added [`span-lite`](https://github.com/martinmoene/span-lite) to the includes directory of `CommonLibSSE` and managed to successfully compile that lib.

However I can't get the `MyFirstPlugin` CommonLibSSE example plugin to compile:

![ForceIncludes](https://user-images.githubusercontent.com/1505923/85914147-c73af380-b808-11ea-8e21-7388606221a3.PNG)

I'm getting the error `Cannot open include file: 'ForceInclude.h': No such file or directory`. I'm very confused because I don't see this `ForceIncludes.h` file mentioned anywhere. It's pointing to the `#include "version.h"` in `main.cpp`.

Don't know if this is helpful but these are the properties of the project:

![properties](https://user-images.githubusercontent.com/1505923/85914293-3238fa00-b80a-11ea-9ac3-e646827d416b.PNG)

Edit: I got rid of that error by removing `ForceInclude.h` from the "Forced Include File" option in Configuration Properties > C/C++ > Advanced but I still have 3022 compiler errors so I clearly have something set up incorrectly.

**Comment by Ryan-rsm-McKenzie** [comment]
It's been a long time since I've written these tutorials and a lot of things have changed since then. I've gone ahead and updated the "Getting Started" tutorial and example project to reflect how I develop plugins these days.

**Comment by thallada** [comment]
@Ryan-rsm-McKenzie awesome, thanks. Works perfectly for me now!
