### ISSUE TITLE
write_call and write_branch jumps to the wrong address if called multiple times

### ISSUE THREAD

**Issue by Vermunds** [Ryan-rsm-McKenzie/CommonLibSSE#28]
The first time these functions are called, they work as expected, but calling them multiple times results in jumping to/calling the address specified in the first one.

Example:

```
SKSE::Trampoline& trampoline = SKSE::GetTrampoline();
trampoline.write_call<5>(someID.address(), Foo);
trampoline.write_call<5>(someID.address() + 0x5, Bar);
```

This should result in a call to `Foo` and an another one to `Bar`, but both calls `Foo` instead.

**Comment by Ryan-rsm-McKenzie** [comment]
should be fixed
