### ISSUE TITLE
CommonLib Sample Plugin Tutorial

### ISSUE THREAD

**Issue by TheFBplus** [Ryan-rsm-McKenzie/CommonLibSSE#4]
Hi,Ryan.Do you have any plan to write a tutorial about how to create the first plugin with your CommonLib?I follow the tutorial on this website but I still can't build the project.PS:I am not familiar with C++ 😞 
![微信图片_20190730220118](https://user-images.githubusercontent.com/33896027/62135882-99f27680-b315-11e9-81aa-558e6f1f28ef.png)
![微信图片_20190730220124](https://user-images.githubusercontent.com/33896027/62135900-a1b21b00-b315-11e9-9897-d58c720bb03e.png)

**Comment by Ryan-rsm-McKenzie** [comment]
Just add commlib to the solution like you added the example project

**Comment by TheFBplus** [comment]
Well,actually I've already added them.I think it might have something to do with the including path or there are something more need to be done?can you give me some advice? 
I am so sorry for bothering you with this.

**Comment by Ryan-rsm-McKenzie** [comment]
You need to add commonlib's include folder to your include path

**Comment by TheFBplus** [comment]
Thanks a lot :smile:
