### ISSUE TITLE
How to Install spdlog? Compile Error!

### ISSUE THREAD

**Issue by Super-SZC** [Ryan-rsm-McKenzie/CommonLibSSE#42]
Hi, Ryan! Firstly, thanks for your awesome library!

I try to set up the library and compile the example plugin you provided in "Getting Start" Wiki tutorial.

I following every steps your tutorial told: Install Vcpkg, then install "Xbyak" and "span-lite" using vcpkg.

However, I found that I also need to install "spdlog" to build.

I try to enter command `vcpkg install spdlog:x64-windows-custom`, but it didn't work and said "Source directory D:\vcpkg-master\packages\fmt_x64-windows-static-md does not exist".

Could you please give me some advices on that? Thanks!

**Comment by Ryan-rsm-McKenzie** [comment]
I updated the example project with build instructions

**Comment by Super-SZC** [comment]
Hi, Ryan!

I tried to follow the instructions of the example project. When I tried to run the "bootstrap.ps1" file with powershell, it show me this error:

```
File D:\ExamplePlugin-CommonLibSSE-master\ExamplePlugin-CommonLibSSE-master\bootstrap.ps1 cannot be loaded. 

The file D:\ExamplePlugin-CommonLibSSE-master\ExamplePlugin-CommonLibSSE-master\bootstrap.ps1 is not digitally signed.

You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
```
Anything I did wrong?

**Comment by Super-SZC** [comment]
Manage to solve the "digitally signed" above, but now the powersheel report me this error:

`Error: Cannot find definition for package `commonlibsse`.`

I can ensure I  add the environment variable entitled "CommonLibSSEPath" as your wiki told, since I had build the project successfully in old version which not required spdlog.

Please help....

**Comment by Super-SZC** [comment]
Never mind. I was finally able to build the plugin and load it into the game. didn't use the newest example project you provided, but an older one.

I install all the dependency library under "x64-windows-static" using vcpkg, then I change the "Runtime Library" to "Multi-threaded Debug (/MTd)", and compile the dll plugin successfully. Loaded it into the game and created the log.
