### ISSUE TITLE
Rename function "IAnimationGraphManagerHolder::NotifyAnimationGraph" to "SendAnimationEvent"?

### ISSUE THREAD

**Issue by max-su-2019** [Ryan-rsm-McKenzie/CommonLibSSE#47]
I thinks the function name "NotifyAnimationGraph" is a little confused and may easily cause people don't know the meaning and features of this function.（At least it confuse me for a period )

Why not rename it as "SendAnimationEvent" which is a much familiar name that most of Bethesda game modder will know? It actually do the almost same thing with "SendAnimationEvent" papryus function and console command, right?

https://www.creationkit.com/index.php?title=SendAnimationEvent_-_Debug

**Comment by Ryan-rsm-McKenzie** [comment]
It's based off of the real name of the function

**Comment by max-su-2019** [comment]
Fine. So, Bethesda has name this function as "NotifyAnimationGraph", but when they call this function in papyrus scirpt and console command, they name it in a different name called "SendAnimationEvent". And cause "SendAnimationEvent" became the name we know instead of "NotifyAnimationGraph".

And I suppose there will be more developers likes me that will confused by the name of this function when they making project that depends on Commonlib.

I suggest that maybe you can add another member function to "Actor" class that name "SendAnimationEvent" would allow developers to find out the function easier?

Or maybe at least you can add a line of comment under the "Notify Animation Graph" function, to remind other developers that this function is actually doing the things that “SendAnimationEvent' done?
