### ISSUE TITLE
Unable to build any plugin

### ISSUE THREAD

**Issue by Vermunds** [Ryan-rsm-McKenzie/CommonLibSSE#56]
The library itself compiles just fine.
However, any plugin that relies on it fails to compile with the same error messages. [Example output here](https://pastebin.com/eSE3VabK).
From what I can tell, it seems like the problem is caused by conflicts between the constants defined in `SKSE/Impl/WinAPI.h` and in `Winnt.h`.
Just including `RE/Skyrim.h` or `SKSE/SKSE.h` in my projects seems to include both implicitly (without including them these constants are not defined at all).
Any advice/fix would be appreciated.

**Comment by Ryan-rsm-McKenzie** [comment]
include windows.h (or xbyak) after commonlib

**Comment by Vermunds** [comment]
Neither makes any difference. I don't even use xbyak in this case.

**Comment by Ryan-rsm-McKenzie** [comment]
show me your code

**Comment by Vermunds** [comment]
It happen even with no code (aside from the load and query functions), but here is the one I'm trying, it's a rather simple one:
https://github.com/Vermunds/TimeFormatChanger-SE/tree/Test

**Comment by Ryan-rsm-McKenzie** [comment]
add `SPDLOG_COMPILED_LIB` to your defines

**Comment by Vermunds** [comment]
Okay, that certainly helped. I'm now getting unresolved externals in WinAPI. At least it's something different. Anyways, here is it:
```4>CommonLibSSE.lib(WinAPI.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoSizeA referenced in function "unsigned int __cdecl SKSE::WinAPI::GetFileVersionInfoSize(char const *,unsigned int *)" (?GetFileVersionInfoSize@WinAPI@SKSE@@YAIPEBDPEAI@Z)
4>CommonLibSSE.lib(WinAPI.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoSizeW referenced in function "unsigned int __cdecl SKSE::WinAPI::GetFileVersionInfoSize(wchar_t const *,unsigned int *)" (?GetFileVersionInfoSize@WinAPI@SKSE@@YAIPEB_WPEAI@Z)
4>CommonLibSSE.lib(WinAPI.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoA referenced in function "bool __cdecl SKSE::WinAPI::GetFileVersionInfo(char const *,unsigned int,unsigned int,void *)" (?GetFileVersionInfo@WinAPI@SKSE@@YA_NPEBDIIPEAX@Z)
4>CommonLibSSE.lib(WinAPI.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoW referenced in function "bool __cdecl SKSE::WinAPI::GetFileVersionInfo(wchar_t const *,unsigned int,unsigned int,void *)" (?GetFileVersionInfo@WinAPI@SKSE@@YA_NPEB_WIIPEAX@Z)
4>CommonLibSSE.lib(WinAPI.obj) : error LNK2019: unresolved external symbol VerQueryValueA referenced in function "bool __cdecl SKSE::WinAPI::VerQueryValue(void const *,char const *,void * *,unsigned int *)" (?VerQueryValue@WinAPI@SKSE@@YA_NPEBXPEBDPEAPEAXPEAI@Z)
4>CommonLibSSE.lib(WinAPI.obj) : error LNK2019: unresolved external symbol VerQueryValueW referenced in function "bool __cdecl SKSE::WinAPI::VerQueryValue(void const *,wchar_t const *,void * *,unsigned int *)" (?VerQueryValue@WinAPI@SKSE@@YA_NPEBXPEB_WPEAPEAXPEAI@Z)
```

**Comment by Ryan-rsm-McKenzie** [comment]
rebase on upstream

**Comment by Vermunds** [comment]
I'm on the latest version already.

**Comment by Ryan-rsm-McKenzie** [comment]
link version.lib

**Comment by Vermunds** [comment]
And that did it. It compiles now. A lot of warnings though, but I'm not complaining. It works.
Thanks for the help.

**Comment by Ryan-rsm-McKenzie** [comment]
This process is a lot easier if you use the cmake integration

**Comment by Vermunds** [comment]
Yeah I figured. I'm just not too used to CMake yet.
