### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Geehral** [Ryan-rsm-McKenzie/CommonLibSSE#57]
may sound stupid but i follow ur get started step for step the first part was working and my dll is working
but evrything after commonlibsse dont make sense to me u using commands my system say not found and pointing to files they just dont exist.

what i', doing wrong could u maybe help me?

**Comment by Ryan-rsm-McKenzie** [comment]
Follow the instructions on the example plugin
https://github.com/Ryan-rsm-McKenzie/ExamplePlugin-CommonLibSSE
