### ISSUE TITLE
Linker error for RE::BaseExtraList::GetDisplayName()

### ISSUE THREAD

**Issue by RealAntithesis** [Ryan-rsm-McKenzie/CommonLibSSE#6]
I'm trying my hand at creating an SKSE plugin using CommonLibSSE. So far so good, but there appears to be some differences between the SKSE implementation for BaseExtraList and CommonLibSSE. In my case, GetDisplayName(TESForm* a_type) appears to be missing from BaseExtraList.cpp, which comes up with an linker error when compiling (prior to this, finding the definition brings up the SKSE implementation). What was the intent here (and any suggestions to resolve)?

**Comment by Ryan-rsm-McKenzie** [comment]
it should be fixed now

**Comment by Ryan-rsm-McKenzie** [comment]
If you need help with development you can join the dev server at https://discord.gg/M6NgVJB

**Comment by RealAntithesis** [comment]
Great, thanks!
