### ISSUE TITLE
BSTHashMap.h

### ISSUE THREAD

**Issue by USAFrenzy** [Ryan-rsm-McKenzie/CommonLibSSE#65]
Hey Ryan,
First, thank you for all the time spent making this library. I was hoping to figure out If I missed a step in configuring the build.
When I clone the repo, have all dependencies set to go, and then build this library via cmake, it generates perfectly fine. However, when I open up vs2019 and build CommonLibSSE - it throws a few errors in compilation pertaining to the bit functions. When I add ```#include <bit>``` to BSTHashMap.h, it finishes the build without any issues and while I haven't tested linking to it yet, seems to be fine now. Not sure if it was an oversight on my part for a file or external dependency that already provides the definition for those or not.

Thank you in advance

<details>
  <summary>Before/After Photos</summary>

Before:
![Before](https://user-images.githubusercontent.com/49297331/106362248-c9f64d80-62ef-11eb-96e4-468b5fa6941e.png)

After:
![After](https://user-images.githubusercontent.com/49297331/106362247-c95db700-62ef-11eb-89db-eefcd0aa6293.png)

</details>

**Comment by Ryan-rsm-McKenzie** [comment]
This project uses the latest vs preview

**Comment by USAFrenzy** [comment]
Ah, see, I thought I had updated to the latest vs2019 but apparently I'm still using 16.8.4 stable release (after my confusion rose to a all new high on settings, decided to check the release notes vs. my version lol) That's on me - I'm going to go install 16.9 Preview 3 now and give this a whirl again as I see they've added quite a lot in the 16.9 previews. Thank you for the speedy reply!

**Comment by USAFrenzy** [comment]
And that fixed it - Sorry For The Issue!
