### ISSUE TITLE
Trampoline allocation failing

### ISSUE THREAD

**Issue by 65a** [Ryan-rsm-McKenzie/CommonLibSSE#66]
I haven't examined Trampoline.h in great detail, but it looks like it would benefit from a similar approach as below. The below commit fixed the Trampoline under wine/proton (not that it isn't also a wine bug).

https://github.com/ianpatt/skse64/commit/4a1e1219578890fb8cfb077daf08b386855ec62f

**Comment by Ryan-rsm-McKenzie** [comment]
My trampoline doesn't overflow when calculating the range
https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/a0b569de94ac992f56966dff5b8313224e29f6d3/include/SKSE/Trampoline.cpp#L77-L78

**Comment by 65a** [comment]
Interesting. I am getting an allocation failure with EngineFixes64 under wine, and was hoping it was a similar issue with calculating the lower bound

https://bugs.winehq.org/show_bug.cgi?id=44893

**Comment by Ryan-rsm-McKenzie** [comment]
It's much more likely it simply failed to preload and never allocated a trampoline in the first place

**Comment by 65a** [comment]
`skse64 plugin preloader - d3dx9_42
exe path: C:\steam\steamapps\common\skyrim special edition\skyrimse_steamless.exe
loaded into SkyrimSE.exe or SkyrimVR.exe, proxying SkyrimSE d3dx9_42 funcs and registering preload hook
success`

`[2021-01-31 20:09:05.232] [info] [main.cpp:137] beginning pre-load patches
[2021-01-31 20:09:05.233] [critical] [SKSE/Trampoline.h:187] Failed to handle allocation request`

https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/a0b569de94ac992f56966dff5b8313224e29f6d3/include/SKSE/Trampoline.h#L187

I think that this means we are failing to allocate the trampoline, called from

https://github.com/aers/EngineFixesSkyrim64/blob/ccde2fdd1a33a356fb43dbb491b868fbddf00508/src/main.cpp#L97

but it's not clear to me how Initialize() gets called, since the error references a line in SKSE_PluginQuery

The reason I suspected the min limit was that wine seems to allocate from the bottom, but any info on how I can debug this further and figure out why it won't load on wine is much appreciated

**Comment by Ryan-rsm-McKenzie** [comment]
That fact that it doesn't print the version should tell you it never preloaded
https://github.com/aers/EngineFixesSkyrim64/blob/ccde2fdd1a33a356fb43dbb491b868fbddf00508/src/main.cpp#L86
That trampoline was never allocated, and you can't allocate from nothing, so it fails.

**Comment by 65a** [comment]
I assume d3dx9_ dll is supposed to call Initialize() on the DLL? I am definitely seeing the preloader dll get loaded
`00c4:trace:loaddll:build_module Loaded L"C:\\steam\\steamapps\\common\\skyrim special edition\\d3dx9_42.dll" at 0000000000420000: native`

And I see here: https://github.com/aers/skse64_plugin_preloader/blob/master/d3dx9_42.cpp that it is supposed to trigger the Initialize function in the DLL. The last thing the DLL logs is success.

I'm not sure I understand the detour code, but I see it is doing something with "api-ms-win-crt-runtime-l1-1-0.dll", which is provided by wine runtime and not the windows DLL, which could be the issue?

**Comment by 65a** [comment]
That is the problem for wine, since that dll is already intercepted by wine, it never hooks. I compiled skse_plugin_preloader without the initterm dance, and it works fine. Thanks!
