### ISSUE TITLE
How to find class vtables using RTTI addresses in database?

### ISSUE THREAD

**Issue by nbilling** [Ryan-rsm-McKenzie/CommonLibSSE#69]
It seems like one would be able to use the class RTTI ids to get an address inside that class' TypeDescriptor and then read the corresponding vtable address from it. When I try this I get what looks like bogus vtable addresses, and in fact all of the pointers to function pointers in between the ".?AVxxx" mangled names in SkyrimSE.exe appear to be the same.

This is with me trying something like:
`(RE::msvc::type_info*)(RE::RTTI_PlayerCharacter.address())->_vftable`

This is consistent with what I see when I inspect the same bits of memory in SkyrimSE.exe eg. in Ghidra. So, I'm not suggesting anything is broken or wrong, but I'm very curious how one would use the RTTI offsets in the db together with the CommonLIbSSE utilities to find any particular vtable. Am I doing this entirely wrong and I'm meant to use the RTTI offsets for something else entirely?

**Comment by Ryan-rsm-McKenzie** [comment]
Hi, I'd recommend you read [this](http://www.openrce.org/articles/full_view/23) article if you would like to learn more about rtti and how it works. However, it seems unlikely that you actually need to find arbitrary references to vtables using the rtti. It sounds like you are a bit misguided.

**Comment by nbilling** [comment]
Thanks for that link! I'm curious why you say I don't need to use the rtti to find references to the vtables. Is that because there's a different way to find the addresses of virtual functions using CommonLibSSE, or because I should be using a more straight-forward approach to reversing the c++ in skyrimse.exe in the first place? Apologies if I'm asking dumb questions, I mean well :)

**Comment by Ryan-rsm-McKenzie** [comment]
vtables are embedded within objects. If you need to invoke a virtual method, then you can do so with an instance of the object. If you want to find vtables during static analysis, then I would recommend you use IDA pro.
