### ISSUE TITLE
issue involving steamless

### ISSUE THREAD

**Issue by jfmherokiller** [Ryan-rsm-McKenzie/CommonLibSSE#72]
I noticed an issue if I use the default settings of steamless.
![EngineFixes.dll -- SKSE/Trampoline.h(187): Failed to handle allocation request](https://i.imgur.com/QQfBjuU.png)
(the exect code location can be seen here https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/master/include/SKSE/Trampoline.h#L187)
This error comes from EngineFixes but it could probably come from other plugins as well but i havent tested that.
It comes from the fact that steamless in its default configuration "shrinks" the exe.
![size comparison between original and modified exe](https://i.imgur.com/3e56LD3.png)
This missing size comes from the "bind" section of the exe which is removed by default (If i had to guess enginefixes uses this section in its calculations)
The fix is mainly to just enable the bind section as seen below.
![enable bind section in settings](https://i.imgur.com/OHFjqez.png)

**Comment by Ryan-rsm-McKenzie** [comment]
Engine Fixes isn't being pre-loaded. This has nothing to do with CLib.
