### ISSUE TITLE
vcpkg port

### ISSUE THREAD

**Issue by Pospelove** [Ryan-rsm-McKenzie/CommonLibSSE#74]
Hey! First, thanks for the project. We use ComonLibSSE as a submodule in  [SkyrimPlatform](https://github.com/skyrim-multiplayer/skyrim-platform/tree/master/submodules) and it's obviously better than SKSE build we have. But since both projects use vcpkg with manifests, it would be reasonable to add CommonLibSSE to vcpkg as a port. I'll try it out. Creating this issue to discuss details, potential building issues, etc.

**Comment by Ryan-rsm-McKenzie** [comment]
I would recommend you don't add it as a port to vcpkg. Due to the highly volatile nature of the project, it is best consumed via git submodules, rather than painstakingly updating the commit hash + download hash everytime you wish to pull the latest commit.

**Comment by Pospelove** [comment]
Sound reasonable but we update CommonLibSSE quite rare. Actually, we never updated it, just used a fixed version. Now we just want vcpkg to build our project with its dependencies (including CommonLibSSE with its dependencies).

**Comment by Ryan-rsm-McKenzie** [comment]
You can use an overlay port for this

**Comment by Pospelove** [comment]
You are absolutely right once again, but... Why shouldn't I make it available to the whole world? I think plugin devs would be happy seeing that vcpkg supports CommonLibSSE out of the box. Actually, CommonLibSSE is a C++ library with many users. And many of them also update very rarely.

**Comment by Ryan-rsm-McKenzie** [comment]
Commonlib updates frequently, and it takes about a week to merge a pr into vcpkg. The port would constantly be out of date, and I have no interest in maintaining it.

**Comment by Pospelove** [comment]
>  The port would constantly be out of date
Doesn't seem to actually be very bad.

But ok, we'll begin with overlay ports. Thanks for answering, closing this for now.

Btw, https://github.com/Ryan-rsm-McKenzie/ExamplePlugin-CommonLibSSE may become much easier to launch. Just one command forcing CMake and vcpkg to do their job.
