### ISSUE TITLE
Compile Instructions

### ISSUE THREAD

**Issue by thakyZ** [Ryan-rsm-McKenzie/CommonLibSSE#8]
I was wondering if you could write compiling instructions for if your mods would be needed to be updated for a newer SKSE version in the future.
I was attempting earlier this week to compile your mods for SKSE64 1.5.97 but I didn't know where to get the offsets. So if you could write a documentation on how to build your plugins so the community may be able to upload a temporary fix until you release an official version whenever a new SKSE version comes out.
Thank you.

**Comment by Ryan-rsm-McKenzie** [comment]
I have no interest in teaching people how to do reverse engineering. Please save this page for issues related to the actual library.
