### ISSUE TITLE
Is there a way to mimic Game.IsObjectFavorited?

### ISSUE THREAD

**Issue by SteveTownsend** [Ryan-rsm-McKenzie/CommonLibSSE#84]
Is there any equivalent in CLSSE of [this SKSE function on the Game script ](https://www.creationkit.com/index.php?title=IsObjectFavorited_-_Game)? 
_Bool IsObjectFavorited(Form form)
Returns whether the specified base form is favorited by the player._
I can script around it if not but C++ call would be preferable

**Comment by Ryan-rsm-McKenzie** [comment]
I would just reimplement it in C++ if I were you

**Comment by SteveTownsend** [comment]
Thanks for getting back. I'll see if I can work out how to do that, it was
not clear to me how that would work. Any pointers for CLSSE hooks on
favourited status?

**Comment by Vermunds** [comment]
Iterate trough the players inventory, until you find your item. If it has an `ExtraHotkey` attached to it, it is favorited.
For spells, use `MagicFavorites`.
